//navbar
export const SHOW_MOBILE_NAV = "SHOW_MOBILE_NAV"
export const SHOW_AUTH_DIALOG = "SHOW_AUTH_DIALOG"
export const IS_AUTH = "IS_AUTH"
export const TOP_NAVS = "TOP_NAVS"
//main page
export const MAIN_SLIDER_SLIDS = "MAIN_SLIDER_SLIDS"
export const MAIN_WHY_WE_ARE = "MAIN_WHY_WE_ARE"
export const MAIN_QUESTION_ANSWER = "MAIN_QUESTION_ANSWER"
export const MAIN_NEWS = "MAIN_NEWS"
export const SERVISES = "SERVISES"
//footer
export const PAYMENT = "PAYMENT"
export const SOCIAL = "SOCIAL"
export const CONTACT = "CONTACT"

//routes
export const ROUTES = "ROUTES"
export const SHOW_MORE_ROUTES = "SHOW_MORE_ROUTES"
export const ROUTE_DETAIL = "ROUTE_DETAIL"
export const ROUTE_SERVISES = "ROUTE_SERVISES"

//offers
export const OFFERS = "OFFERS"
export const OFFERS1 = "OFFERS1"
export const SELECTED_OFFERS_ID = "SELECTED_OFFERS_ID"
export const SELECT_OFFER_ID = "SELECT_OFFER_ID"

export const ON_BASKET_OFFERS_COMMIT = "BASKET_OFFERS_COMMIT"
export const SHOW_MOBILE_BASKET_IN_OFFERS = "SHOW_MOBILE_BASKET_IN_OFFERS"
export const SHOW_MOBILE_FILTER_IN_OFFERS = "SHOW_MOBILE_FILTER_IN_OFFERS"
//bus
export const BUS = "BUS"
export const SHOW_PLACEMENT_DIALOG = "SHOW_PLACEMENT_DIALOG"
//dialog

//basket
export const BASKET = "BASKET"
export const CREATE_BASKET = "CREATE_BASKET"
export const ADD_BASKET_ITEM = "ADD_BASKET_ITEM"
export const REMOVE_BASKET_ITEM = "REMOVE_BASKET_ITEM"
export const BASKET_COMMIT = "BASKET_COMMIT"
export const CLEAR_BASKET = "CLEAR_BASKET"
export const SHOW_MOBILE_BASKET_BOOKING = "SHOW_MOBILE_BASKET_BOOKING"
export const SHOW_MOBILE_BASKET_DETAIL = "SHOW_MOBILE_BASKET_DETAIL"

//ALERT
export const ALERT = "ALERT"
export const TOGGLE_ALERT = "TOGGLE_ALERT"

//paymentSystem
export const SHOW_PAYMENT_SYTEM_DIALOG = "SHOW_PAYMENT_SYTEM_DIALOG"
export const PAYMENT_SYSTEM = "PAYMENT_SYSTEM"
export const SELECT_PAYMENT_SYSTEM = "SELECT_PAYMENT_SYSTEM"

//timer
export const TIMER = "TIMER"

//booking
export const AGREEMENT_DIALOGS = "AGREEMENT_DIALOGS"
export const TOGGLE_AGREEMENT_DIALOGS = "TOGGLE_AGREEMENT_DIALOGS"
export const BOOKING_VALID = "BOOKING_VALID"
export const REMOVE_PASSENGER_FROM_BASKET = "REMOVE_PASSENGER_FROM_BASKET"
export const SELECT_DIRECTION = "SELECT_DIRECTION"
export const SELECTED_DIRECTION = "SELECTED_DIRECTION"
export const REMOVE_DIRECTION_FROM_BASKET = "REMOVE_DIRECTION_FROM_BASKET"
export const SAVE_PREV_BASKET = "SAVE_PREV_BASKET"
//passenger
export const SELECTED_PASSENGER_ID = "SELECTED_BASKET_PASSENGER_ID"
export const SELECT_PASSENGER_ID = "SELECTED_BASKET_PASSENGER_ID"

//placements
export const CHANGE_PLACEMET = "CHANGE_PLACEMENT"
export const COMMIT_CHANGE_PLACEMET = "COMMIT_CHANGE_PLACEMET"

//nav
export const PERSONAL_NAV = "PERSONAL_NAV"
export const MAIN_NAV = "MAIN_NAV"

//users
export const USER_INFO = "USER_INFO"
export const CURRENT_OFFERS = "CURRENT_OFFERS"
export const HISTORY_OFFERS = "HISTORY_OFFER"
export const ALL_STATUS = "ALL_STATUS"
export const PASSENGER_LIST = "PASSENGER_LIST"

//dialog

//drawer
export const SHOW_MOBILE_PERSONAL_MENU = "SHOW_MOBILE_PERSONAL_MENU"

export const ON_SYNC_DEFAULT = "ON_SYNC_DEFAULT"
export const ON_LOCATION_HREF = "ON_LOCATION_HREF"
export const LOCATION_HREF = "LOCATION_HREF"

//busRental
export const BUS_RENTAL = "BUS_RENTAL"
export const SHOW_BUSRENTAL_RATE_DIALOG = "SHOW_BUSRENTAL_RATE_DIALOG"
export const SELECTED_BUSRENTAL_ID = "SELECTED_BUSRENTAL_ID"
export const BASKET_RENTAL = "BASKET_RENTAL"
export const BASKET_RENTAL_COMMIT = "BASKET_RENTAL_COMMIT"
export const ADD_BASKET_RENTAL = "ADD_BASKET_RENTAL"
export const ON_BASKET_RENTAL_COMMIT = "ON_BASKET_RENTAL_COMMIT"
